verbose: false
api: http://127.0.0.1:5000
conformance-tests-script: test_scripts/run_conformance_tests.sh
prepare-environment-script: test_scripts/prepare_environment_java.sh
unittests-script: test_scripts/run_unittests.sh