verbose: false
api: https://api.codeplain.ai
conformance-tests-script: configs/scripts/run_conformance_tests_java.sh
prepare-environment-script: configs/scripts/prepare_environment_java.sh
unittests-script: configs/scripts/run_unittests_java.sh
